version = 0.1

[default.global.parameters]
stack_name = "htmx-experiment"
region = "eu-west-2"

[default.validate.parameters]
lint = true

[default.deploy.parameters]
resolve_s3 = true
s3_prefix = "htmx-experiment"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
